RED = \033[0;31m
GREEN = \033[0;32m
NO_COLOR = \033[0m


init:
        @echo "${GREEN}terraform init"
        @terraform init

plan: 
        @echo "${GREEN}terraform plan"
        @terraform plan 

apply: 
        @echo "${GREEN}terraform apply"
        @terraform apply

destroy: 
        @echo "${GREEN}terraform destory"
        @terraform destroy  -auto-approve
