init:
        @echo "${GREEN}terraform init"
        @terraform init

plan: 
        @echo "${GREEN}terraform plan"
        @terraform plan 

apply: 
        @echo "${GREEN}terraform apply"
        @terraform apply

destroy: 
        @echo "${GREEN}terraform destory"
        @terraform destroy  -auto-approve
